image:
  repository: eu.gcr.io/sap-se-gcp-scp-k8s/remedy-controller/remedy-controller-azure
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1
resources: {}
vpa:
  enabled: false
  updatePolicy:
    updateMode: "Auto"

manager:
  metricsPort: 6000
targetManager:
  metricsPort: 6001

controllers:
  publicipaddress:
    concurrentSyncs: 5
  virtualmachine:
    concurrentSyncs: 5
  service:
    concurrentSyncs: 5
  node:
    concurrentSyncs: 5

disableControllers: []
targetDisableControllers: []

config:
  clientConnection:
    acceptContentTypes: application/json
    contentType: application/json
    qps: 100
    burst: 130
  azure:
    orphanedPublicIPRemedy:
      requeueInterval: 1m
      deletionGracePeriod: 5m
      maxGetAttempts: 5
      maxCleanAttempts: 5
    failedVMRemedy:
      requeueInterval: 1m
      maxGetAttempts: 5
      maxReapplyAttempts: 5

imagePullSecret:
  registry: ''
  username: ''
  password: ''

cloudProviderConfig: ~