apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels" . | indent 4 }}
data:
  config.yaml: |
    ---
    apiVersion: remedy.config.gardener.cloud/v1alpha1
    kind: ControllerConfiguration
{{- if .Values.config.clientConnection }}
    clientConnection:
      acceptContentTypes: {{ required ".Values.config.clientConnection.acceptContentTypes is required" .Values.config.clientConnection.acceptContentTypes }}
      contentType: {{ required ".Values.config.clientConnection.contentType is required" .Values.config.clientConnection.contentType }}
      qps: {{ required ".Values.config.clientConnection.qps is required" .Values.config.clientConnection.qps }}
      burst: {{ required ".Values.config.clientConnection.burst is required" .Values.config.clientConnection.burst }}
    azure:
      orphanedPublicIPRemedy:
        requeueInterval: {{ required ".Values.config.azure.orphanedPublicIPRemedy.requeueInterval is required" .Values.config.azure.orphanedPublicIPRemedy.requeueInterval }}
        deletionGracePeriod: {{ required ".Values.config.azure.orphanedPublicIPRemedy.deletionGracePeriod is required" .Values.config.azure.orphanedPublicIPRemedy.deletionGracePeriod }}
        maxGetAttempts: {{ required ".Values.config.azure.orphanedPublicIPRemedy.maxGetAttempts is required" .Values.config.azure.orphanedPublicIPRemedy.maxGetAttempts }}
        maxCleanAttempts: {{ required ".Values.config.azure.orphanedPublicIPRemedy.maxReapplyAttempts is required" .Values.config.azure.orphanedPublicIPRemedy.maxCleanAttempts }}
      failedVMRemedy:
        requeueInterval: {{ required ".Values.config.azure.failedVMRemedy.requeueInterval is required" .Values.config.azure.failedVMRemedy.requeueInterval }}
        maxGetAttempts: {{ required ".Values.config.azure.failedVMRemedy.maxGetAttempts is required" .Values.config.azure.failedVMRemedy.maxGetAttempts }}
        maxReapplyAttempts: {{ required ".Values.config.azure.failedVMRemedy.maxReapplyAttempts is required" .Values.config.azure.failedVMRemedy.maxReapplyAttempts }}
{{- end }}
