apiVersion: v1
kind: Secret
metadata:
  name: {{ include "name" . }}-image-pull-secret
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels" . | indent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecret | b64enc | quote }}
